# permissions for end users to view ipmiendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipmiendpoint-viewer-role
rules:
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - ipmiendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - ipmiendpoints/status
  verbs:
  - get
