# permissions for end users to view redfishendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redfishendpoint-viewer-role
rules:
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - redfishendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - redfishendpoints/status
  verbs:
  - get
