---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - baremetalnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - baremetalnodes/finalizers
  verbs:
  - update
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - baremetalnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - ipmiendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - ipmiendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - ipmiendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - redfishendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - redfishendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - redfishendpoints/status
  verbs:
  - get
  - patch
  - update
