# permissions for end users to view systems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-viewer-role
rules:
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - systems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bmo.bmcgo.dev
  resources:
  - systems/status
  verbs:
  - get
